### ISSUE TITLE
Running as sudo in Linux means that the home directory is going to be /root

### ISSUE THREAD

**Issue by itsme-alan** [patriksvensson/cupboard#13]
Running as sudo in Linux shouldn't be required.

**Comment by patriksvensson** [comment]
Yes, I agree. Will make this configurable for each provider and only require sudo if a used provider needs it.

**Comment by patriksvensson** [comment]
Should be fixed in the next preview version. Now, either a resource provider can say that it needs administrative permissions, or you can opt-in for it when declaring the resource.

```csharp
context.Resource<PowerShellScript>("Install Chocolatey")
    .Script("~/install-chocolatey.ps1")
    .RequireAdministrator()
    .Unless("if (Test-Path \"$($env:ProgramData)/chocolatey/choco.exe\") { exit 1 }")
    .After<RegistryKey>("Set execution policy")
    .After<Download>("https://chocolatey.org/install.ps1");
```
