### ISSUE TITLE
Question: Will it support MacOs or Linux

### ISSUE THREAD

**Issue by guy-lud** [patriksvensson/cupboard#27]
Hello,

I've gone over the code and demo an i understand that in current state it does not support MacOs or Linux. Do you believe it should be included. If so when is it planed. Will you accept help with that?

Thank you

**Comment by just1a-person** [comment]
It does support macOS and Linux. The only thing is that macOS/Linux specific functionality (like support for apt/brew.. etc.) isn't added yet.

**Comment by guy-lud** [comment]
I saw that `PowerShell` is supported but `Shell/Bash/Zsh` etc. Isn't I probably missed it.

**Comment by patriksvensson** [comment]
@guy-lud For shell you could just use `Exec`

**Comment by guy-lud** [comment]
@patriksvensson , Thank you.
I'll give it a try
