### ISSUE TITLE
Compiler errors when following README

### ISSUE THREAD

**Issue by antoniovalentini** [patriksvensson/cupboard#28]
elo 👋 

I've stepped into some compiler errors while following the README and implementing the `Chocolatey` example.

If you say that I'm not missing anything and they can be fixed, I'd be more than happy to open a PR.

- dotnet: 5.0
- Cupboard: 0.4.0
- OS: Windows

### Missing closing curly bracket
The `Chocolatey` sealed class is missing a closing curly bracket at the very end.

### Unable to check `OSPlatform`
The `IF` statement inside the `MyWindowsComputer` catalog example, is showing the error `Cannot apply operator '!=' to operands of type 'Cupboard.Fact' and 'System.Runtime.InteropServices.OSPlatform'`.

To fix it I have to access the `Value` property and cast it to `OSPlatform`:
```C#
if ((OSPlatform)context.Facts["os.platform"].Value != OSPlatform.Windows)
{
    return;
}
```

### Missing `Build` function
I can't use the `Run(string[] args)` function after the `AddCatalog<MyWindowsComputer>()` one, during the CupboardHost builder creation.
To fix it, I have to call `Build()` and then `Run(args)`:
```C#
return CupboardHost.CreateBuilder()
    .AddCatalog<MyWindowsComputer>()
    .Build()
    .Run(args);
```

**Comment by patriksvensson** [comment]
@antoniovalentini: Thanks for your report!

`Missing closing curly bracket`: Great catch! Thanks!
`Unable to check OSPlatform`: Yes, you're correct. This needs to be fixed. Preferably with `if (context.Facts.IsWindows())`
`Missing Build function`: This will be available in 0.5.0, so this doesn't need to be fixed.

If you want to submit a PR for this, it would be much appreciated! 🙏
