### ISSUE TITLE
remove Mono.Posix.NETStandard ?

### ISSUE THREAD

**Issue by jetersen** [patriksvensson/cupboard#43]
@patriksvensson I was exploring the last native dependency: Mono.Posix.NETStandard, I tried removing it and I could still build the project.

is there any reason for it?

https://github.com/patriksvensson/cupboard/blob/5b934948cc3446fe5ab3d1945df9faf46e488c9e/src/Cupboard.Core/Cupboard.Core.csproj#L16

**Comment by patriksvensson** [comment]
@jetersen No, it should be implicitly imported via `Spectre.IO` so should be able to remove that one.

**Comment by jetersen** [comment]
Right next question, any reason Spectre.IO is pulling it in 🤔

Right, only to call create symlink which got support for in dotnet 6.

I'll see if I can create a PR that removes Mono.Posix.NETStandard on dotnet 6 😃

**Comment by jetersen** [comment]
https://github.com/spectresystems/spectre.io/pull/2 👏

**Comment by jetersen** [comment]
Right with https://github.com/spectresystems/spectre.io/pull/2 it actually means we now need to explicit depend on it as we use it for file access API
